// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANXJKxExljbMy7ev8avACUxuaDiD7e4zc',
    appId: '1:21815196383:web:3f0ba4fb9e57c167aec76a',
    messagingSenderId: '21815196383',
    projectId: 'lilydoll-cbd74',
    authDomain: 'lilydoll-cbd74.firebaseapp.com',
    storageBucket: 'lilydoll-cbd74.appspot.com',
    measurementId: 'G-QQP76YRN6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK9YfjyM0PTD4IamAHSPUbkxB6Gg4BRUI',
    appId: '1:21815196383:android:e60b3d043842eb3caec76a',
    messagingSenderId: '21815196383',
    projectId: 'lilydoll-cbd74',
    storageBucket: 'lilydoll-cbd74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwNbdFm-bNgBF6_Au55fYfMCvvc5JLzyk',
    appId: '1:21815196383:ios:619c30a2d1661265aec76a',
    messagingSenderId: '21815196383',
    projectId: 'lilydoll-cbd74',
    storageBucket: 'lilydoll-cbd74.appspot.com',
    iosBundleId: 'com.example.projectLily',
  );
}
